"""
Project Euler Problem 45
========================

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle     T[n]=n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal   P[n]=n(3n-1)/2  1, 5, 12, 22, 35, ...
Hexagonal    H[n]=n(2n-1)    1, 6, 15, 28, 45, ...

It can be verified that T[285] = P[165] = H[143] = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

upper = 100000

tri = set(n*(n+1)/2 for n in range(1, upper))
pent = set(n*(3*n-1)/2 for n in range(1, upper))
hex = set(n*(2*n-1) for n in range(1, upper))

print sorted(list(tri.intersection(pent).intersection(hex)))[2]